/* eslint-disable no-process-env */
/* eslint-disable no-underscore-dangle */

const _REACT_APP_VERSION = process.env.REACT_APP_VERSION;

const _REACT_APP_ENTERPRISE = process.env.REACT_APP_ENTERPRISE === 'true';
const _REACT_APP_VENDOR = process.env.REACT_APP_VENDOR === 'true';
const _REACT_APP_IGNORE_AUTH = process.env.REACT_APP_IGNORE_AUTH === 'true';
const _REACT_APP_FIREBASE_PRODUCTION =
  process.env.REACT_APP_FIREBASE_PRODUCTION === 'true';

const _REACT_APP_FIREBASE_API_KEY = process.env.REACT_APP_FIREBASE_API_KEY;
const _REACT_APP_FIREBASE_AUTH_DOMAIN =
  process.env.REACT_APP_FIREBASE_AUTH_DOMAIN;
const _REACT_APP_FIREBASE_PROJECT_ID =
  process.env.REACT_APP_FIREBASE_PROJECT_ID;
const _REACT_APP_FIREBASE_STORAGE_BUCKET =
  process.env.REACT_APP_FIREBASE_STORAGE_BUCKET;
const _REACT_APP_FIREBASE_MESSAGING_SENDER_ID =
  process.env.REACT_APP_FIREBASE_MESSAGING_SENDER_ID;
const _REACT_APP_FIREBASE_APP_ID = process.env.REACT_APP_FIREBASE_APP_ID;
const _REACT_APP_FIREBASE_MEASUREMENT_ID =
  process.env.REACT_APP_FIREBASE_MEASUREMENT_ID;

export const REACT_APP_VERSION = _REACT_APP_VERSION;
export const REACT_APP_ENTERPRISE = _REACT_APP_ENTERPRISE;
export const REACT_APP_VENDOR = _REACT_APP_VENDOR;
export const REACT_APP_IGNORE_AUTH = _REACT_APP_IGNORE_AUTH;
export const REACT_APP_FIREBASE_PRODUCTION = _REACT_APP_FIREBASE_PRODUCTION;
export const REACT_APP_FIREBASE_API_KEY = _REACT_APP_FIREBASE_API_KEY;
export const REACT_APP_FIREBASE_AUTH_DOMAIN = _REACT_APP_FIREBASE_AUTH_DOMAIN;
export const REACT_APP_FIREBASE_PROJECT_ID = _REACT_APP_FIREBASE_PROJECT_ID;
export const REACT_APP_FIREBASE_STORAGE_BUCKET =
  _REACT_APP_FIREBASE_STORAGE_BUCKET;
export const REACT_APP_FIREBASE_MESSAGING_SENDER_ID =
  _REACT_APP_FIREBASE_MESSAGING_SENDER_ID;
export const REACT_APP_FIREBASE_APP_ID = _REACT_APP_FIREBASE_APP_ID;
export const REACT_APP_FIREBASE_MEASUREMENT_ID =
  _REACT_APP_FIREBASE_MEASUREMENT_ID;

export const NODE_ENV = process.env.NODE_ENV ?? '';